### ISSUE TITLE
App rejected by playstore

### ISSUE THREAD

**Issue by Ankitsinh-siddhiinfosoft** [Mindinventory/Lassi-Android#38]
In my app only storage related function is choose file and upload on server ,this library use All storage permission so app rejected on play store cause of android.permission.MANAGE_EXTERNAL_STORAGE this.

Is there possible if we can use this library without this permission?

**Comment by jayrhalani** [comment]
Yes same issue happening with me.

**Comment by chiragmi** [comment]
@Ankitsinh-siddhiinfosoft @jayrhalani 
Thanks for using this library

We have provided "android.permission.MANAGE_EXTERNAL_STORAGE" permission access at the user side. Now you can fully manage it according to the app feature. FYI, If Android device SDK is >= 30 and wants to access the document (only for choose the non-media file) then add "android.permission.MANAGE_EXTERNAL_STORAGE" permission in your app otherwise library won't allow you to access documents. Kindly check the sample app for more detail.

Kindly check this with latest version 
**implementation 'com.github.Mindinventory:Lassi:0.2.2'**

**Comment by Ankitsinh-siddhiinfosoft** [comment]
@chiragmi Thanks

**Comment by arsalanImtiaz455** [comment]
same issue for me I have send video as well but google reject my App for rollout. Please guide me what to do?
